version: '3.8'

services:
  fluentd:
    build: .
    volumes: 
      - type: bind
        source: ./fluentd
        target: /fluentd
      - ./log:/var/log
    env_file: .env
    ports:
      - "24224:24224"