version: "3.8"

services: 
  sandbox:
    build: .
    tty: true
    volumes:
      - type: bind
        source: ./src
        target: /go/src
    environment: 
      - GO111MODULE=on
    ports:
      - "8080:8080"