version: "3.8"
services:
  grafana:
    image: grafana/grafana:8.3.3
    container_name: grafana
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./provisioning/datasources
        target: /etc/grafana/provisioning/datasources
      - type: bind
        source: ./provisioning/dashboards
        target: /etc/grafana/provisioning/dashboards
      - type: bind
        source: ./provisioning/notifiers
        target: /etc/grafana/provisioning/notifiers
      - type: bind
        source: ./dashboards
        target: /var/lib/grafana/dashboards/default
  
  loki:
    image: grafana/loki
    container_name: loki
    volumes:
      - type: bind
        source: ./loki/loki-local-config.yaml
        target: /etc/loki/local-config.yaml
      - type: bind
        source: ./loki/rules
        target: /loki/rules
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
  
  promtail:
    image: grafana/promtail:2.4.1
    volumes:
      - ./promtail/log:/var/log
      - ./promtail/promtail-local-config.yaml:/etc/promtail/config.yml
    ports:
      - "9080:9080"
    command: -config.file=/etc/promtail/config.yml