version: '3.9'
services:
  protobuf:
    build: .
    volumes:
      - "./:/go/src"
    command: [
      "protoc",
      "-I=./proto",
      "--go_out=./proto/go",
      "--go-grpc_out=./proto/go",
      "--go_opt=paths=source_relative",
      "--go-grpc_opt=paths=source_relative", 
      "proto/sample.proto"
    ]
