version: '3.9'
services:
  app:
    # 下のissueがcloseになるまでbullseyeを使用する
    # https://github.com/prisma/prisma/issues/8478
    image: node:18.0.0-bullseye 
    volumes:
      - "./:/app"
    working_dir: /app
    command: ["npm","run","dev"]
    ports:
      - "3000:3000"
    init: true
    environment:
      DATABASE_URL: "mysql://root:admin@db:3306/employees"
      NODE_ENV: dev
    depends_on:
      db:
        condition: service_healthy

  db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}  
      # MYSQL_DATABASE: ${DB_DATABASE}
      # MYSQL_USER: ${DB_USER}
      # MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:  
      - ./mysql/data:/var/lib/mysql
      # - ./mysql/initdb.d:/docker-entrypoint-initdb.d # test_dbを使用するので、今回は必要ない
      - ./mysql/log:/var/log/mysql
      - ./mysql/cnf:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 1s
      retries: 3