version: '3.9'
services:
  app:
    # 下のissueがcloseになるまでbullseyeを使用する
    # https://github.com/prisma/prisma/issues/8478
    image: node:18.0.0-bullseye 
    volumes:
      - "./:/app"
    working_dir: /app
    command: ["npm", "start"]
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mysql:8.0-debian
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}  
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:  
      - ./mysql/data:/var/lib/mysql
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/log:/var/log/mysql
      - ./mysql/cnf:/etc/mysql/conf.d
    ports:
      - "3306:3306"