name: Go

on:
  push:
    branches: [ main ]
    paths:
      - 'golang/restful/*.go'
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: 'golang/restful'
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v cmd/server.go

    - name: Test
      run: go test -v ./...

    - name: Upload Coverage
      uses: codecov/codecov-action@v1
      #with:
        #token: ${{ secrets.CODECOV_TOKEN }}
