- name: debug
  vars:
    source_release_version: 1.22.15-20221112
  debug:
    msg: "{{ source_release_version }} イメージはバージョン1.24より小さい" 
  when: ( source_release_version | split('-') | first ) is version(1.24.0, '>')

- name: debug
  vars:
    source_release_version: 1.24.7-20221112
  debug:
    msg: "{{ source_release_version }} イメージはバージョン1.24より小さい" 
  when: ( source_release_version | split('-') | first ) is version(1.24.0, '>')

- name: debug
  vars:
    source_release_version: 1.22.15-20221112
  debug:
    msg: "{{ source_release_version }} イメージはバージョン1.24より小さい" 
  when: ( source_release_version | split('-') | first ) is version(1.24.0, '>')

- name: debug
  vars:
    source_release_version: amazon-eks-node-1.24-v20221112
  debug:
    msg: "{{ source_release_version }} イメージはバージョン1.24より小さい" 
  when: ( source_release_version | split('-') | first ) is version(1.24.0, '>')
